# !/usr/bin/python3
# -*- coding: utf-8 -*-

SETTINGS_PRIORITY = 100

PYFORMS_MATPLOTLIB_ENABLED = False
PYFORMS_WEB_ENABLED = False
PYFORMS_GL_ENABLED = False
PYFORMS_VISVIS_ENABLED = False

DEFAULT_INTENTS_PATH = None
